version: 1.0
phases:
  build:
    commands:
      - echo Packaging booking_app.jar file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/booking_app
  discard-paths: yes